### ISSUE TITLE
[SCAN] sub-03_ses-008

### ISSUE THREAD

**Issue by FrancoisPgm** [courtois-neuromod/triplets#15]
### Setup

- [X] biopac
- [ ] eyetracker
- [X] game controller

### general notes

The eyetracker would freeze in a different way than usual, the CPU count would still update, only the image was frozen, moving the mouse didn't help. It happened every time after several re-launching of the task and a reboot of both the computer and the camera, so we decided to do the session without the eyetracker. 
The camera was left on the mirror, we just didn't use the --eyetracking flag on the script.

### task-triplets_run-01 completion

- [X] series was completed.

### task-triplets_run-01 issues

physio signal quality issue

### task-triplets_run-01 notes

low EDA (around 3)

### task-triplets_run-02 completion

- [X] series was completed.

### task-triplets_run-02 issues

physio signal quality issue

### task-triplets_run-02 notes

low EDA 

### task-triplets_run-03 completion

- [X] series was completed.

### task-triplets_run-03 notes

low EDA
