### ISSUE TITLE
[SCAN] sub-03_ses-009

### ISSUE THREAD

**Issue by pravishsainath** [courtois-neuromod/triplets#17]
### Setup

- [ ] biopac
- [ ] eyetracker
- [ ] game controller

### general notes

- The eye tracker was blurry despite maximum sharpness, the pupil tracking was wobbly and produced larger spherical clusters in the calibration because of the tracker motion.
- GSR signal was always zero.

Same for all three runs.

### task-triplets_run-01 completion

- [ ] series was completed.

### task-triplets_run-02 completion

- [ ] series was completed.

### task-triplets_run-03 completion

- [ ] series was completed.
