### ISSUE TITLE
[SCAN] sub-03_ses-003

### ISSUE THREAD

**Issue by me-pic** [courtois-neuromod/triplets#5]
### Setup

- [X] biopac
- [X] eyetracker
- [X] game controller

### task-wordsfamiliarity_run-01 completion

- [ ] series was completed.

### task-wordsfamiliarity_run-01 notes

Wrong sequence: triplets instead of Words familiarity (task ended before the end of the sequence)

I think the controller was not plugged properly in the acquisition room (sub03 tried to press A but nothing append, when I checked the controller wired, it was a bit loose in the port)

### task-wordsfamiliarity_run-02 completion

- [ ] series was completed.

### task-wordsfamiliarity_run-03 completion

- [ ] series was completed.
